ports:
  - port: 3000
    onOpen: open-preview
tasks:
  - before: if [[ -z "$experiment" ]]; then cd playground/guilherme; else cd playground/$experiment; fi
    command: nvm install 16.9.1 && npm install && npm start && y
